apiVersion: apps/v1
kind: Deployment
metadata:
  name: polkadot-panic-alerter
spec:
  selector:
    matchLabels:
      app: polkadot-panic-alerter
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: polkadot-panic-alerter
    spec:
      containers:
      - name: polkadot-api-server
        image: simplyvc/polkadot_api_server:1.13.1
        volumeMounts:
        - name: polkadot-api-server-config-vol
          mountPath: /opt/polkadot_api_server/config
        resources:
          limits:
            cpu: 0
      - name: panic-alerter
        image: simplyvc/panic_polkadot:2.0.1
        resources:
          limits:
            cpu: 0
        volumeMounts:
        - name: polkadot-panic-alerter-config-vol
          mountPath: /opt/panic_polkadot/config
        - name: polkadot-panic-alerter-logs-alerts
          mountPath: /opt/panic_polkadot/logs/alerts
        - name: polkadot-panic-alerter-logs-general
          mountPath: /opt/panic_polkadot/logs/general
      volumes:
        - name: polkadot-api-server-config-vol
          configMap:
            name: polkadot-api-server-config
        - name: polkadot-panic-alerter-config-vol
          configMap:
            name: polkadot-panic-alerter-config-vol
        - name: polkadot-panic-alerter-logs-alerts
          emptyDir: {}
        - name: polkadot-panic-alerter-logs-general
          emptyDir: {}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: polkadot-api-server-config
  namespace: default
data:
  user_config_main.ini: |
    [api_server]
    port = 3000
  user_config_nodes.ini: |
    [node_1]
    node_name = polkadot_private_node
    ws_url = ws://polkadot-private-node-0.polkadot-private-node:9944
    [node_2]
    node_name = polkadot_sentry_node_0
    ws_url = ws://polkadot-sentry-node-0.polkadot-sentry-node:9944
    [node_3]
    node_name = polkadot_sentry_node_1
    ws_url = ws://polkadot-sentry-node-1.polkadot-sentry-node:9944
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: polkadot-panic-alerter-config-vol
  namespace: default
data:
  user_config_main.ini: |
    [general]
    unique_alerter_identifier = polkadot-alerter
    
    [telegram_alerts]
    enabled = True
    bot_token = aaaa:-iqwonieqownr
    bot_chat_id = -486750096
    
    [email_alerts]
    enabled = False
    smtp = my.smtp.com
    from = alerter@email.com
    to = user@email.com
    user = my_username
    pass = my_password
    
    [twilio_alerts]
    enabled = False
    account_sid = abcd1234efgh5678ABCD1234EFGH567890
    auth_token = 1234abcd5678efgh1234abcd5678efgh
    twilio_phone_number = +12025551234
    phone_numbers_to_dial = +12025551235;+12025551236;+12025551237
    
    [telegram_commands]
    enabled = True
    bot_token = xxx:1bci
    bot_chat_id = -41333333
    
    [redis]
    enabled = False
    host = localhost
    port = 6379
    password = HMASDNoiSADnuiasdgnAIO876hg967bv99vb8buyT8BVuyT76VBT76uyi
    
    [mongo]
    enabled = False
    host = localhost
    port = 27017
    db_name = panic
    user = username
    pass = aKoJ8hHa897gZGiuHiugOIGoiuygOIuugO879gtLnPGkjhgOgiuo76uyi
    
    [api]
    polkadot_api_endpoint = http://127.0.0.1:3000
    
    [periodic_alive_reminder]
    enabled = False
    interval_seconds = 3600
    email_enabled = False
    telegram_enabled = True
    mongo_enabled = True
  user_config_nodes.ini: |
    [node_1]
    node_name = polkadot-private-node
    node_ws_url = ws://polkadot-private-node-0.polkadot-private-node:9944
    node_is_validator = false
    is_archive_node = true
    monitor_node = true
    use_as_data_source = true
    #stash_account_address = D3bm5eAeiRezwZp4tWTX4sZN3u8nXy2Fo21U59smznYHu3F
    stash_account_address =
    
    [node_2]
    node_name = polkadot-sentry-node-0
    node_ws_url = ws://polkadot-sentry-node-0.polkadot-sentry-node:9944
    node_is_validator = false
    is_archive_node = true
    monitor_node = true
    use_as_data_source = false
    stash_account_address =
    
    [node_3]
    node_name = polkadot-sentry-node-1
    node_ws_url = ws://polkadot-sentry-node-1.polkadot-sentry-node:9944
    node_is_validator = false
    is_archive_node = true
    monitor_node = true
    use_as_data_source = true
    stash_account_address =
  user_config_repos.ini: |
    [repo_0]
    repo_name = Substrate
    repo_page = w3f/substrate/
    monitor_repo  = true
    
    [repo_1]
    repo_name = Polkadot
    repo_page = paritytech/polkadot/
    monitor_repo = true
  internal_config.ini: |
    [logging]
    logging_level = INFO
    
    telegram_commands_general_log_file = logs/general/telegram_commands.log
    github_monitor_general_log_file_template = logs/general/github_monitor_{}.log
    node_monitor_general_log_file_template = logs/general/node_monitor_{}.log
    blockchain_monitor_general_log_file_template = logs/general/blockchain_monitor_{}.log
    # Log files with {} are Python template strings, where {} is replaced with
    # text that makes the log file name specific to the process that logs to it.
    # For example, node_monitor_{}.log may become node_monitor_validator.log
    
    alerts_log_file = logs/alerts/alerts.log
    redis_log_file = logs/general/redis.log
    mongo_log_file = logs/general/mongo.log
    general_log_file = logs/general/general.log
    
    [twilio]
    twiml_instructions_url = https://twimlets.com/echo
    
    [mongo]
    coll_alerts_prefix = alerts_
    
    [redis]
    redis_database = 10
    redis_test_database = 11
    
    redis_twilio_snooze_key = twilio_snooze
    redis_github_releases_key_prefix = github_releases_
    redis_node_monitor_alive_key_prefix = node_monitor_alive_
    redis_node_monitor_session_index_key_prefix = node_monitor_session_index_
    redis_node_monitor_last_height_checked_key_prefix = node_monitor_last_height_checked_
    redis_blockchain_monitor_alive_key_prefix = blockchain_monitor_alive_
    redis_periodic_alive_reminder_mute_key = alive_reminder_mute_
    
    redis_twilio_snooze_key_default_hours = 1.0
    redis_periodic_alive_reminder_mute_key_default_hours = 1.0
    
    redis_node_monitor_alive_key_timeout = 86400
    redis_node_monitor_last_height_key_timeout = 86400
    redis_blockchain_monitor_alive_key_timeout = 86400
    # This timeout makes the 'recent updates' in the Telegram status temporary, so
    # that if a monitor is switched off, its last update eventually disappears.
    
    [monitoring_periods]
    node_monitor_period_seconds = 10
    node_monitor_max_catch_up_blocks = 500
    blockchain_monitor_period_seconds = 10
    github_monitor_period_seconds = 3600
    # These define how often a monitor runs an iteration of its monitoring loop
    
    [alert_intervals_and_limits]
    downtime_alert_interval_seconds = 900
    validator_peer_danger_boundary = 1
    validator_peer_safe_boundary = 2
    full_node_peer_danger_boundary = 5
    max_time_alert_between_blocks_authored = 1800
    github_error_interval_seconds = 3600
    no_change_in_height_interval_seconds = 7200
    no_change_in_height_first_warning_seconds = 3600
    change_in_bonded_balance_threshold = 1
    # These limit the number of alerts of a specific type received using either
    # time intervals (seconds) or boundaries (blocks or danger boundaries). The
    # type of alert received is also affected in some cases.
    
    [links]
    validators_polkascan_link = https://polkascan.io/pre/kusama-cc3/session/validator
    validators_polkastats_link = https://polkastats.io
    
    block_polkascan_link_prefix = https://polkascan.io/pre/kusama-cc3/block/
    block_boka_network_link_prefix = https://boka.network/#/Kusama/block/
    block_subscan_link_prefix = https://kusama.subscan.io/block/
    
    tx_polkascan_link_prefix = https://polkascan.io/pre/kusama-cc3/transaction/
    
    github_releases_template = https://api.github.com/repos/{}releases
    # This is a Python template string, where {} is replaced with (for example) w3f/substrate/
    # so that the complete link becomes: https://api.github.com/repos/w3f/substrate/releases
