apiVersion: v1
kind: Service
metadata:
  name: polkadot-sentry-node-rpc
spec:
  ports:
  - port: 9944
  selector:
    app: polkadot-sentry-node
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: polkadot-sentry-node
  namespace: dot
spec:
  selector:
    matchLabels:
      app: polkadot-sentry-node # Label selector that determines which Pods belong to the StatefulSet
                 # Must match spec: template: metadata: labels
  serviceName: "polkadot-sentry-node"
  replicas: 2
  template:
    metadata:
      labels:
        app: polkadot-sentry-node # Pod template's label selector
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - name: polkadot-sentry-node
        image: parity/polkadot:v0.7.28
        args: [ "--sentry", "--pruning=archive", "--wasm-execution", "Compiled" ]
        ports:
        - containerPort: 9944
          name: dot-ws-port
        volumeMounts:
        - name: polkadot-sentry-node-pv-claim
          mountPath: /polkadot
      initContainers:
      - name: polkadot-archive-downloader
        image: polkadot-archive-downloader
        volumeMounts:
        - name: polkadot-sentry-node-pv-claim
          mountPath: /polkadot
  volumeClaimTemplates:
  - metadata:
      name: polkadot-sentry-node-pv-claim
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: local-ssd
      resources:
        requests:
          storage: 30Gi
