kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: local-ssd
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
allowVolumeExpansion: true
---
apiVersion: v1
kind: Service
metadata:
  name: polkadot-private-node
spec:
  ports:
  - port: 9615
    name: health
  - port: 9944
    name: rpc
  selector:
    app: polkadot-private-node
  clusterIP: None
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: polkadot-private-node-policy
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: polkadot-private-node
  policyTypes:
  - Ingress
  - Egress
  egress:
  - ports:
    - port: 53
      protocol: TCP
    - port: 53
      protocol: UDP
    - port: 443
      protocol: TCP
  - ports:
    - port: 30333
      protocol: TCP
    - port: 9933
      protocol: TCP
    to:
    - podSelector:
        matchLabels:
          app: polkadot-sentry-node
  ingress:
  - ports:
    - port: 9615
      protocol: TCP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: polkadot-private-node
spec:
  selector:
    matchLabels:
      app: polkadot-private-node # Label selector that determines which Pods belong to the StatefulSet
                 # Must match spec: template: metadata: labels
  serviceName: "polkadot-private-node"
  replicas: 1
  template:
    metadata:
      labels:
        app: polkadot-private-node # Pod template's label selector
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - name: polkadot-private-node
        image: polkadot-private-node
        ports:
        - containerPort: 9615
          name: metrics-port
        - containerPort: 9944
          name: dot-ws-port
        volumeMounts:
        - name: polkadot-private-node-pv-claim
          mountPath: /polkadot
      - name: polkadot-api-server
        image: simplyvc/polkadot_api_server:1.9.1
        volumeMounts:
        - name: polkadot-api-server-config-vol
          mountPath: /opt/polkadot_api_server/config
      volumes:
        - name: polkadot-api-server-config-vol
          configMap:
            name: polkadot-api-server-config-private
      initContainers:
      - name: polkadot-archive-downloader
        image: polkadot-archive-downloader
        args:
        - "$(ARCHIVE_URL)"
        env:
        - name: ARCHIVE_URL
          valueFrom:
            configMapKeyRef:
              name: polkadot-configmap
              key: ARCHIVE_URL
        volumeMounts:
        - name: polkadot-private-node-pv-claim
          mountPath: /polkadot
  volumeClaimTemplates:
  - metadata:
      name: polkadot-private-node-pv-claim
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: local-ssd
      resources:
        requests:
          storage: 30Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: polkadot-api-server-config-private
  namespace: default
data:
  user_config_main.ini: |
    [api_server]
    port = 3000
  user_config_nodes.ini: |
    [local]
    node_name = polkadot_private_node
    ws_url = ws://127.0.0.1:9944
