apiVersion: v1
kind: Service
metadata:
  name: polkadot-sentry-node-rpc
spec:
  ports:
  - port: 9933
  selector:
    app: polkadot-sentry-node
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: polkadot-sentry-node
spec:
  ports:
  - port: 30333
  selector:
    app: polkadot-sentry-node
  clusterIP: None
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: polkadot-sentry-node-policy
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: polkadot-sentry-node
  policyTypes:
  - Ingress
  - Egress
  egress:
  - ports:
    - port: 53
      protocol: TCP
    - port: 53
      protocol: UDP
    - port: 443
      protocol: TCP
    - port: 9615
      protocol: TCP
    - port: 30333
      protocol: TCP
    - port: 30334
      protocol: TCP
    - port: 30100
      protocol: TCP
  ingress:
  - ports:
    - port: 30333
      protocol: TCP
  - ports:
    - port: 9944
      protocol: TCP
    from:
    - podSelector:
        matchLabels:
          app: polkadot-panic-alerter
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: polkadot-sentry-node
spec:
  selector:
    matchLabels:
      app: polkadot-sentry-node
  serviceName: polkadot-sentry-node
  replicas: 2
  template:
    metadata:
      labels:
        app: polkadot-sentry-node
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - name: polkadot-sentry-node
        image: polkadot-sentry-node
        ports:
        - containerPort: 9933
          name: dot-rpc-port
        - containerPort: 30333
          name: dot-p2p-port
        volumeMounts:
        - name: polkadot-sentry-node-pv-claim
          mountPath: /polkadot
        envFrom:
        - configMapRef:
            name: polkadot-configmap
        resources:
          limits:
            cpu: 0
      volumes:
      - name: polkadot-node-keys
        secret:
          secretName: polkadot-node-keys
      initContainers:
      - name: polkadot-node-key-configurator
        image: polkadot-node-key-configurator
        volumeMounts:
        - name: polkadot-sentry-node-pv-claim
          mountPath: /polkadot
        - name: polkadot-node-keys
          mountPath: /polkadot-node-keys
      - name: polkadot-archive-downloader
        image: polkadot-archive-downloader
        volumeMounts:
        - name: polkadot-sentry-node-pv-claim
          mountPath: /polkadot
        env:
        - name: ARCHIVE_URL
          valueFrom:
            configMapKeyRef:
              name: polkadot-configmap
              key: ARCHIVE_URL
  volumeClaimTemplates:
  - metadata:
      name: polkadot-sentry-node-pv-claim
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: local-ssd
      resources:
        requests:
          storage: 50Gi
